### ISSUE TITLE
Initiative site is created along with initiative

### ISSUE THREAD

**Issue by ManushiM** [esridc/hub-py#42]
Steps to test:
* Site is created and is visible as an item in the initiative editor
* Clicking view/edit redirects correctly
* Site is added to Collaboration group on AGOL

@ajturner 

While this can be done using the Python API like:
```
site = gis.content.add(site item dictionary)
site.update(data)
``` 

does this warrant for creating `class Site()` now since it is a crucial concept anyway?

**Comment by ajturner** [comment]
please add specific details to `site item dictionary`. 
I think it would be useful to have a class, so 

```python
mySite = myHub.site.create(title='Site Title', ...)
```

then yes, we should allow cloning, something like:

```python
myNewSite = myHub.site.clone(mySite)
```
