### ISSUE TITLE
v1 functionality for Site class

### ISSUE THREAD

**Issue by ManushiM** [esridc/hub-py#51]
Functionality supported:
```
>>> hub.sites.add(title=title, group_id, domain=None, initiative=None)
>>> site.update()
>>> site.delete()
>>> hub.sites.get(siteId)
>>> hub.sites.search(initiative=None, creator/owner=None)

**Comment by ManushiM** [comment]
Refer - https://github.com/ArcGIS/Hub/blob/master/site.md

**Comment by ManushiM** [comment]
Checkpoints for site creation
* Open Data site
1. New item is added
2. Domain is set
3. Od group_id is updated in item.properties
4. Item.data = that of new OD site as in UI

* Initiative site
1. New item is added
2. Domain is set
3. Add item to initiative collaboration group
4. Set group in item.properties
5. Item.data = that of new initiative site as in UI.

**Comment by ManushiM** [comment]
@dbouwman am I missing anything in these ^ checkpoints?

**Comment by dbouwman** [comment]
Ok... so - what you are trying to replicate is the "core" of the `site-service`



Specifically the `create(...)` fn, and parts of `fromTemplate(...)` and `ensureUniqueDomainName(...)`

https://github.com/ArcGIS/opendata-ui/blob/master/packages/ember-arcgis-layout-services/addon/services/site-service.js#L636

https://github.com/ArcGIS/opendata-ui/blob/master/packages/ember-arcgis-layout-services/addon/services/site-service.js#L878

Along with the `registerSiteAsApplication(...)` function in the `domain-service` 

https://github.com/ArcGIS/opendata-ui/blob/master/packages/ember-arcgis-layout-services/addon/services/domain-service.js#L309

---

You need to verify that the domain is not currently used... we do that by issuing a `GET` to the domain service like `https://opendataqa.arcgis.com/utilities/domains/dave-private-1-dc.hubqa.arcgis.com` - if we get a 404 in response, we know the domain is available. There is different portal logic.

For automated site creation, we have logic that increments the requested subdomain...
so if `myfancysite` is the requested subdomain, that becomes `myfancysite-{{orgUrlKey}}.hub{{ENV}}.arcgis.com`. If that is in use, we then check `myfancysite-1-{{orgUrlKey}}.hub{{ENV}}.arcgis.com` etc

For the javascript API's we use, the item.data is set when we create the item... not sure if that's an option w/ the python api.

Looking at the code, the process is more like this:

- check if requested subdomain is available, increment if necessary. We do this before calling the `create(...)` fn - look at the `fromTemplate(...)` fn. That's also where we do any interpolation (aka "AdLib") 

At this point we'd have the json structure of the item... the hash is structured like `{item:{...}, data: {...}}` and we have helpers that know how to serialize that into the mess that the AGO API wants anyhow... steps are...

- create & protect the item
- AGO Only: create the domain system entry (need the item Id for this step)
- create and protect any needed groups
- share site item to groups 
- register the site item as an application, and assign the domain as a valid redirect uri
- update site item w/ the groupIds, and clientKey (from the app registration)
- AGO Only: then register the site item w/ the opendata backend - this is messy, and hopefully not needed for much longer
