### ISSUE TITLE
Prevent Site domains from being too long

### ISSUE THREAD

**Issue by ajturner** [esridc/hub-py#71]
The Python API needs to prevent Sites from having a subdomain longer than 63 characters. It’s [a limit of DNS](https://en.wikipedia.org/wiki/Subdomain) and was added to our UI. But our Python also needs to prevent bad URL

**Comment by ManushiM** [comment]
@ajturner https://github.com/esridc/hub-py/blob/046f025e5c3d348d6b9509966838dafba7f25515/arcgishub/sites.py#L169
